# Generated by Django 5.2.5 on 2025-08-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devEUI', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fCnt', models.IntegerField()),
                ('data_hex', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('rx_info', models.JSONField()),
                ('tx_info', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='api.device')),
            ],
            options={
                'unique_together': {('device', 'fCnt')},
            },
        ),
    ]
